[model]
# model name or local path, overridden by our runtime script
name = "{{MODEL_NAME}}"

[output]
outdir = "/data/output"
wav_filename = "out.wav"

[generate]
gen_text = "{{GEN_TEXT}}"
# other options (speed, cfg etc) can be added
