model:
  name: F5TTS_v1_Base_v2
  tokenizer: accent
  tokenizer_path: null
  backbone: UNetT
  arch:
    dim: 1024
    depth: 24
    heads: 16
    ff_mult: 4
    text_mask_padding: false
    pe_attn_head: 1
  mel_spec:
    target_sample_rate: 24000
    n_mel_channels: 100
    hop_length: 256
    win_length: 1024
    n_fft: 1024
    mel_spec_type: vocos
  vocoder:
    is_local: false
    local_path: null

# Путь к весам (относительно yaml или абсолютный)
ckpt_file: /root/.cache/huggingface/hub/models--Misha24-10--F5-TTS_RUSSIAN/snapshots/*/F5TTS_v1_Base_v2/model_last_inference.safetensors

# Обязательные параметры для инференса (по аналогии с оригинальными yaml)
inference:
  use_amp: false
  device: cpu
  batch_size: 1
